public class frmDictionary extends javax.swing.JFrame {
    String [] symbolArr;
    //declares array to store element symbols
    String [] nameArr;
    //declares array to store element names
    /**
     * 
     * @param strElementSymbol: symbol of element being searched for name 
     */
    public void SymbolSearch(String strElementSymbol){
        for (int i = 0; i < symbolArr.length; i ++){
            if (symbolArr[i].equals(strElementSymbol)){
                lblSymbolSearchResult.setText("Result: " + nameArr[i]);
                //update text with results
            }
        }
    }
    /**
     * 
     * @param strElementName: name of element being searched for symbol
     */
    public void NameSearch(String strElementName){
        for (int i = 0; i < nameArr.length; i ++){
            if (nameArr[i].equals(strElementName)){
                lblNameSearchResult.setText("Result: " + symbolArr[i]);
                //updates text with results
            }
        }
    }   
    int intPoints;
    //declare variable to store points
    int intWeight;
    //declare variable to store weight
    boolean hasGlasses;
    //declare variable to store whether user has glasses
    boolean hasFlowers;
    //declare variable to store whether user has flowers   
    public frmDictionary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblSymbolSearchResult = new javax.swing.JLabel();
        txtSymbol = new javax.swing.JTextField();
        btnSymbolSearch = new javax.swing.JButton();
        lblSymbolSearch = new javax.swing.JLabel();
        lblNameSearchResult = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnNameSearch = new javax.swing.JButton();
        lblNameSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnBack.setText("Back to garden");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblSymbolSearchResult.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lblSymbolSearchResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSymbolSearchResult.setText("Result:");
        getContentPane().add(lblSymbolSearchResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(txtSymbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 60, -1));

        btnSymbolSearch.setText("Search");
        btnSymbolSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSymbolSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSymbolSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 90, -1));

        lblSymbolSearch.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        lblSymbolSearch.setText("Look up by element symbol");
        getContentPane().add(lblSymbolSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lblNameSearchResult.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        lblNameSearchResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNameSearchResult.setText("Result:");
        getContentPane().add(lblNameSearchResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, -1));

        btnNameSearch.setText("Search");
        btnNameSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNameSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnNameSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 90, -1));

        lblNameSearch.setFont(new java.awt.Font("Comic Sans MS", 2, 13)); // NOI18N
        lblNameSearch.setText("Look up by element name");
        getContentPane().add(lblNameSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        frmHome frmHome = new frmHome();
        //initalize home JFrame
        frmHome.intPoints = intPoints;
        //transfers points variable
        frmHome.lblPoints.setText("Points: " + intPoints);
        //updates point label in home JFrame
        frmHome.intWeight = intWeight;
        //transfers weight variable
        frmHome.lblWeight.setText(intWeight + " lbs");
        //updates weight label in home JFrame       
        frmHome.hasGlasses = hasGlasses;
        //transfers glasses variable
        if (hasGlasses == true){
            frmHome.lblSunglasses.setVisible(true);
            //shows sunglasses in home JFrame
        }
        frmHome.hasFlowers = hasFlowers;
        //transfers flowers variable
        if (hasFlowers == true){
            frmHome.lblFlowers.setVisible(true);
            //shows flowers in home JFrame
        }
        frmHome.setVisible(true);
        //shows home JFrame
        this.dispose();
        //closes dictionary JFrame
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSymbolSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSymbolSearchActionPerformed
        String strSymbol = txtSymbol.getText();
        //read user input from text field
        lblSymbolSearchResult.setText("Result: No symbol found.");
        //update label text
        SymbolSearch(strSymbol);
        //calls void method to search for name
    }//GEN-LAST:event_btnSymbolSearchActionPerformed

    private void btnNameSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNameSearchActionPerformed
        String strName = txtName.getText();
        //read user input from text field
        lblNameSearchResult.setText("Result: No name found.");
        //update label text
        NameSearch(strName);
        //calls void method to search for symbol       
    }//GEN-LAST:event_btnNameSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNameSearch;
    private javax.swing.JButton btnSymbolSearch;
    private javax.swing.JLabel lblNameSearch;
    private javax.swing.JLabel lblNameSearchResult;
    private javax.swing.JLabel lblSymbolSearch;
    private javax.swing.JLabel lblSymbolSearchResult;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSymbol;
    // End of variables declaration//GEN-END:variables
}
